#!/bin/bash
server_ip=$1
server_port=443
busywait=$2


while :
do
    curl -s --http2 --max-time 0.001 https://$server_ip:$server_port/junk/foo.bin -k -o /dev/null -r 1-100000
    sleep $busywait
done